repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-merge-conflict

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.59.0
    hooks:
      - id: golangci-lint
        args:
          - "--config=.golangci.yaml"

  # Define a custom hook for running go test
  - repo: local
    hooks:
      - id: go-test
        name: Go Test
        entry: bash -c "go test -race -cover $(go list ./...)"
        language: system
        types: [go]
